all:
   hosts:
   vars:
      ansible_user: ansible
      ansible_ssh_user: larkin
      ansible_become_user: root
      ansible_become_method: sudo
   children:
      app:
        children:
        vars:
        hosts:
            vm2:
               ansible_host: 158.160.36.11
            vm3:
               ansible_host: 158.160.36.11
      database:
        children:
        vars:
          postgresql_version: 13
          postgresql_data_directory: /opt/pgsql/data
        hosts:
            vm1:
               ansible_host: 51.250.70.73
      web:
         hosts:
            vm1: