- hosts: localhost
  become: true
  tasks:
    - name: install docker
      ansible.builtin.package:
        name: "{{ item  }}"
        state: latest
        update_cache: true
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: run docker
      ansible.builtin.service:
        name: docker
        state: started