- hosts: nginx
  become: true
  vars:
    username: your_username
    password: your_password
    ssh_key: "your_ssh_public_key"
    php_fpm_server: "158.160.111.9"
  roles:
    - users
    - http

- hosts: php-fpm
  become: true
  vars:
    username: your_username
    password: your_password
    ssh_key: "your_ssh_public_key"
  roles:
    - users
    - php
  