- hosts: all
  become: true
  tasks:
    - name: install postfix
      ansible.builtin.package:
        name: postfix
        state: latest
        update_cache: true
      tags:
        - postfix_install
    - name: remove postfix
      ansible.builtin.package:
        name: postfix
        state: absent
        update_cache: true
      tags:
        - postfix_remove
      