---
# tasks file for dnsmasq
- name: install dnsmasq
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: copy dnsmasq configuration file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: ensure dnsmasq service is started and enabled
  service:
    name: dnsmasq
    state: started
    enabled: yes