---
# tasks file for vsftpd
- name: install vsftpd
  ansible.builtin.package:
    name: vsftpd
    state: present

- name: ensure vsftpd service is started and enabled
  service:
    name: vsftpd
    state: started
    enabled: yes